// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --require ts-node/register ./prisma/seed.ts",
  },
  datasource: {
    // Only include the `url` property when DATABASE_URL is set so its
    // type remains an optional string (not `string | undefined`) which
    // satisfies `exactOptionalPropertyTypes: true`.
    ...(process.env["DATABASE_URL"] ? { url: process.env["DATABASE_URL"] } : {}),
  },
});
